version: 2

job-references:
  mysql_image: &mysql_image
    circleci/mysql:5.6

  php_job: &php_job
    environment:
      - WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
      - WP_CORE_DIR: "/tmp/wordpress/"
      - CIRCLE_PROJECT_REPONAME: "WP-Controllers"
    steps:
      - checkout
      - run:
          name: "Setup Environment Variables"
          command: |
            echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: "Install Dependencies"
          command: |
            sudo apt-get update && sudo apt-get install git subversion
            sudo docker-php-ext-install mysqli
            sudo sh -c "printf '\ndeb http://ftp.us.debian.org/debian sid main\n' >> /etc/apt/sources.list"
            sudo apt-get update && sudo apt-get install mysql-client-5.7

      - run:
          name: "Setup For Tests"
          command: |
            composer global require "phpunit/phpunit=5.7.*"
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash tests/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1

      - run:
          name: "Run Tests"
          command: phpunit


jobs:
  php56-build:
    <<: *php_job
    docker:
      - image: circleci/php:5.6
      - image: *mysql_image

  php70-build:
    <<: *php_job
    docker:
      - image: circleci/php:7.0
      - image: *mysql_image

  php71-build:
    <<: *php_job
    docker:
      - image: circleci/php:7.1
      - image: *mysql_image

  php72-build:
    <<: *php_job
    docker:
      - image: circleci/php:7.2
      - image: *mysql_image

workflows:
  version: 2
  main:
    jobs:
      - php56-build
      - php70-build
      - php71-build
      - php72-build
